import type { FrameworkCompetency } from "@/lib/superAdminCompetencyFrameworks";

/** Seeded from ProofDive Success Drivers & Competency Framework (Final). */
export const DEFAULT_FRAMEWORK_COMPETENCIES: FrameworkCompetency[] = [
  {
    id: "thinking-analytical",
    driverId: "thinking",
    name: "Analytical Thinking",
    definition: "Makes sense of problems by breaking them down, identifying patterns and causes, and using clear reasoning to guide action.",
    coreQuestion: "Can this person reason through problems in a structured, evidence-based way?",
    levels: [
      {
        level: 1,
        label: "Fragmented",
        humanDescriptor: "Describes events without clear structure or reasoning; relies primarily on assumptions or isolated observations, focuses on symptoms rather than causes, and struggles to explain how conclusions were reached.",
        aiDescriptor: "• Lists events without meaningful analysis\n• Relies primarily on assumptions or isolated observations\n• Confuses symptoms with root causes\n• Cannot clearly explain reasoning behind actions or conclusions",
      },
      {
        level: 2,
        label: "Inconsistent",
        humanDescriptor: "Identifies some relevant factors but relies on incomplete or narrow information; reasoning is inconsistent, partially structured, or weakly linked to actions and decisions.",
        aiDescriptor: "• Identifies some contributing factors\n• Uses incomplete or narrow information\n• Reasoning lacks consistency or structure\n• Weak linkage between analysis and resulting actions",
      },
      {
        level: 3,
        label: "Logical",
        humanDescriptor: "Breaks problems into manageable parts, gathers relevant information, compares options logically, and explains conclusions in a clear and traceable way.",
        aiDescriptor: "• Breaks problems into logical parts or components\n• Gathers and uses relevant information\n• Compares options using structured reasoning\n• Links analysis clearly to actions, recommendations, or decisions",
      },
      {
        level: 4,
        label: "Insightful",
        humanDescriptor: "Identifies underlying causes, integrates multiple sources or perspectives, connects relevant patterns, evaluates trade-offs, and adjusts reasoning as new information emerges.",
        aiDescriptor: "• Identifies underlying/root causes\n• Integrates multiple perspectives, signals, or information sources\n• Evaluates trade-offs\n• Adapts reasoning when new information emerges",
      },
      {
        level: 5,
        label: "Elevates",
        humanDescriptor: "Consistently breaks down ambiguous problems into clear, reusable structures; synthesizes diverse information and perspectives into meaningful insight; identifies root causes and downstream implications while simplifying complexity so others can apply the logic independently.",
        aiDescriptor: "• Synthesizes complex or diverse inputs into meaningful insight\n• Simplifies ambiguity into reusable structures or frameworks\n• Anticipates implications or downstream impact\n• Demonstrates transferable reasoning others can apply independently",
      },
    ],
  },
  {
    id: "thinking-prioritization",
    driverId: "thinking",
    name: "Prioritization",
    definition: "Focuses effort where it matters most by weighing importance, urgency, impact, constraints, and trade-offs.",
    coreQuestion: "Can this person decide what matters most and focus effort accordingly?",
    levels: [
      {
        level: 1,
        label: "Unfocused",
        humanDescriptor: "Responds mainly to the most visible or immediate tasks without clear rationale; struggles to distinguish urgency from importance and frequently shifts focus without structured prioritization.",
        aiDescriptor: "• Reacts primarily to immediate requests or pressure\n• Lacks clear prioritization rationale\n• Frequently shifts focus without structure\n• Confuses urgency with importance",
      },
      {
        level: 2,
        label: "Inconsistent",
        humanDescriptor: "Recognizes some priorities but applies prioritization unevenly; tends to focus on one factor, such as deadlines, ease, or visibility, without fully considering impact, trade-offs, or broader outcomes.",
        aiDescriptor: "• Identifies some important tasks or goals\n• Applies prioritization inconsistently\n• Over-focuses on one factor such as deadlines or speed\n• Demonstrates limited trade-off thinking",
      },
      {
        level: 3,
        label: "Deliberate",
        humanDescriptor: "Uses clear criteria to prioritize tasks and decisions, sequences work logically, and explains what should be prioritized, delayed, reduced, or deprioritized.",
        aiDescriptor: "• States clear prioritization criteria\n• Ranks or sequences options logically\n• Explains what was prioritized and why\n• Identifies what was delayed, reduced, or deprioritized",
      },
      {
        level: 4,
        label: "Disciplined",
        humanDescriptor: "Balances competing priorities using clear criteria and conscious trade-offs. Considers stakeholder/customer impact and adjusts sequencing based on constraints, dependencies, or changing realities.",
        aiDescriptor: "• Balances competing priorities using clear criteria\n• Evaluates trade-offs consciously\n• Considers stakeholder/customer impact when prioritizing\n• Adjusts sequencing based on constraints or dependencies",
      },
      {
        level: 5,
        label: "Principles Driven",
        humanDescriptor: "Aligns priorities to broader outcomes and long-term impact; anticipates the consequences of prioritization decisions and helps maintain focus on the highest-value work amid complexity or competing demands.",
        aiDescriptor: "• Aligns priorities to broader outcomes or long-term impact\n• Anticipates downstream consequences of prioritization decisions\n• Maintains focus on highest-value outcomes amid complexity\n• Helps others make clearer prioritization decisions",
      },
    ],
  },
  {
    id: "thinking-decision",
    driverId: "thinking",
    name: "Decision-Making Agility",
    definition: "Makes timely, well-reasoned decisions under uncertainty while balancing information, options, trade-offs, and consequences.",
    coreQuestion: "Can this person make sound decisions under uncertainty while maintaining progress?",
    levels: [
      {
        level: 1,
        label: "Hesitant",
        humanDescriptor: "Avoids making decisions independently or reacts impulsively without sufficient reasoning;",
        aiDescriptor: "• Avoids making decisions independently\n• Delays action excessively due to uncertainty\n• Reacts impulsively without sufficient reasoning\n• Struggles to explain decision rationale",
      },
      {
        level: 2,
        label: "Cautious",
        humanDescriptor: "struggles to act confidently when information is incomplete or situations are unclear.",
        aiDescriptor: "• Makes decisions in familiar or straightforward situations\n• Relies heavily on certainty or external direction\n• Demonstrates inconsistent confidence under ambiguity\n• Considers limited implications or alternatives",
      },
      {
        level: 3,
        label: "Decisive",
        humanDescriptor: "Makes basic decisions in familiar or low-risk situations but becomes uncertain under ambiguity, pressure, or competing inputs; decision quality or speed may vary inconsistently.",
        aiDescriptor: "• Makes timely decisions using available information\n• Explains decision rationale logically\n• Considers likely consequences before acting\n• Takes ownership of decisions made",
      },
      {
        level: 4,
        label: "Adaptive",
        humanDescriptor: "Makes timely and logical decisions using available information, considers likely consequences, and takes responsibility for chosen actions even when certainty is incomplete.",
        aiDescriptor: "• Evaluates trade-offs before deciding\n• Considers multiple options or paths before committing\n• Explains reasoning behind decisions clearly\n• Balances short-term and longer-term consequences",
      },
      {
        level: 5,
        label: "Judgement Driven",
        humanDescriptor: "Evaluates trade-offs consciously, considers multiple options before deciding, and balances immediate needs with longer-term consequences when making decisions.",
        aiDescriptor: "• Anticipates likely consequences before committing to decisions\n• Aligns decisions to broader outcomes or principles\n• Helps others evaluate decisions more clearly\n• Maintains decision quality amid complexity or competing pressures",
      },
    ],
  },
  {
    id: "action-ownership",
    driverId: "action",
    name: "Ownership",
    definition: "Takes responsibility for outcomes, acts without unnecessary prompting, and persists through obstacles until meaningful progress is achieved.",
    coreQuestion: "Can this person take responsibility, act proactively, and drive outcomes to completion?",
    levels: [
      {
        level: 1,
        label: "Passive",
        humanDescriptor: "Waits for direction, avoids responsibility when challenges arise, and relies on others to drive progress or resolve issues.",
        aiDescriptor: "• Waits for direction before acting\n• Avoids responsibility when challenges occur\n• Relies on others to drive progress\n• Leaves issues unresolved or incomplete",
      },
      {
        level: 2,
        label: "Responsive",
        humanDescriptor: "Completes assigned responsibilities when directed and follows through on immediate commitments but rarely takes initiative beyond defined expectations.",
        aiDescriptor: "• Completes assigned tasks when directed\n• Responds appropriately to requests or instructions\n• Follows through on immediate commitments\n• Demonstrates limited initiative beyond assigned scope",
      },
      {
        level: 3,
        label: "Responsible",
        humanDescriptor: "Takes ownership of assigned outcomes, follows through reliably, addresses issues within their control, and can be counted on to complete commitments.",
        aiDescriptor: "• Takes responsibility for assigned outcomes\n• Follows through reliably until completion\n• Addresses issues within their control\n• Honours commitments without excessive supervision",
      },
      {
        level: 4,
        label: "Proactive",
        humanDescriptor: "Identifies opportunities or problems without being prompted, takes initiative to move work forward, overcomes obstacles independently, and maintains momentum toward desired outcomes.",
        aiDescriptor: "• Identifies problems or opportunities independently\n• Takes initiative without being asked\n• Overcomes obstacles or setbacks proactively\n• Drives work forward despite ambiguity or resistance",
      },
      {
        level: 5,
        label: "Outcome Driven",
        humanDescriptor: "Creates momentum beyond their immediate responsibilities, anticipates risks to delivery, drives outcomes through sustained ownership, and helps others achieve successful completion of shared goals.",
        aiDescriptor: "• Anticipates risks that could affect outcomes\n• Creates momentum beyond immediate responsibilities\n• Helps others achieve successful completion\n• Maintains focus on achieving meaningful outcomes rather than simply completing tasks",
      },
    ],
  },
  {
    id: "action-initiative",
    driverId: "action",
    name: "Initiative & Follow-through",
    definition: "Understands who is affected by the work, balances their needs, and creates value through thoughtful decisions and actions.",
    coreQuestion: "Can this person understand, balance, and create value for affected stakeholders?",
    levels: [
      {
        level: 1,
        label: "Self-Focused",
        humanDescriptor: "Focuses primarily on personal tasks, objectives, or convenience with limited awareness of how actions affect customers, users, teammates, or other stakeholders.",
        aiDescriptor: "• Focuses primarily on personal tasks or objectives\n• Demonstrates limited awareness of stakeholder impact\n• Prioritizes personal convenience over stakeholder outcomes\n• Struggles to identify who is affected by decisions",
      },
      {
        level: 2,
        label: "Aware",
        humanDescriptor: "Recognizes stakeholder expectations when they are explicitly communicated but responds reactively rather than proactively; consideration of stakeholder impact is inconsistent.",
        aiDescriptor: "• Recognizes stakeholder expectations when explicitly communicated\n• Responds to stakeholder needs when requested\n• Demonstrates inconsistent stakeholder consideration\n• Focuses mainly on immediate stakeholder requests",
      },
      {
        level: 3,
        label: "Responsive",
        humanDescriptor: "Understands stakeholder needs and incorporates them into decisions and actions; actively considers how work affects others and adjusts approach accordingly.",
        aiDescriptor: "• Identifies relevant stakeholders affected by decisions\n• Considers stakeholder needs when taking action\n• Adjusts approach based on stakeholder impact\n• Balances personal objectives with stakeholder expectations",
      },
      {
        level: 4,
        label: "Balanced",
        humanDescriptor: "Balances the needs of multiple stakeholders, considers competing interests, and makes thoughtful trade-offs while maintaining focus on maximizing stakeholder value.",
        aiDescriptor: "• Balances competing stakeholder needs\n• Evaluates trade-offs between stakeholder interests\n• Considers both short-term and longer-term stakeholder impact\n• Makes decisions that maximize stakeholder value",
      },
      {
        level: 5,
        label: "Anticipatory",
        humanDescriptor: "Anticipates stakeholder needs and downstream impact, creates value beyond stated requirements, and helps others make decisions that better serve stakeholder outcomes.",
        aiDescriptor: "• Anticipates stakeholder needs before they are expressed\n• Considers downstream stakeholder implications\n• Creates value beyond stated requirements\n• Helps others make decisions that improve stakeholder outcomes",
      },
    ],
  },
  {
    id: "action-change",
    driverId: "action",
    name: "Embraces Change",
    definition: "Stays effective when circumstances shift, adapts quickly, and uses change as an opportunity to improve outcomes.",
    coreQuestion: "Can this person adapt effectively and use change to improve outcomes?",
    levels: [
      {
        level: 1,
        label: "Rejects Change",
        humanDescriptor: "Actively resists or avoids change; prefers familiar approaches and struggles to adjust when circumstances, expectations, or priorities shift.",
        aiDescriptor: "• Resists new approaches, processes, or expectations\n• Prefers familiar methods despite evidence that change is needed\n• Expresses frustration or avoidance when circumstances change\n• Struggles to adjust behavior when required",
      },
      {
        level: 2,
        label: "Resistant",
        humanDescriptor: "Accepts change when required but does so reluctantly; makes necessary adjustments but may require guidance, encouragement, or additional time to adapt effectively.",
        aiDescriptor: "• Accepts change when directed or required\n• Makes necessary adjustments after encouragement or support\n• Follows new processes or expectations once established\n• Demonstrates gradual adaptation but limited proactive engagement",
      },
      {
        level: 3,
        label: "Adaptable",
        humanDescriptor: "Adjusts behavior, approach, or priorities effectively when circumstances change; learns what is needed to remain productive and maintain performance.",
        aiDescriptor: "• Adjusts behavior or approach when circumstances change\n• Learns new skills, processes, or ways of working when needed\n• Remains productive despite uncertainty or disruption\n• Adapts priorities or plans appropriately as situations evolve",
      },
      {
        level: 4,
        label: "Driver",
        humanDescriptor: "Uses change as an opportunity to improve outcomes; experiments with new approaches, solves problems created by change, and helps maintain momentum during transitions.",
        aiDescriptor: "• Identifies opportunities created by change\n• Experiments with new approaches to improve outcomes\n• Solves problems arising from changing circumstances\n• Helps maintain progress or performance during transitions",
      },
      {
        level: 5,
        label: "Change Catalyst",
        humanDescriptor: "Recognizes when change is needed, actively champions beneficial change, helps others adapt successfully, and creates momentum that improves outcomes beyond the immediate situation.",
        aiDescriptor: "• Recognizes when change is needed before it becomes unavoidable\n• Actively advocates for beneficial change\n• Helps others adapt successfully to change\n• Creates momentum that improves outcomes beyond the immediate change effort",
      },
    ],
  },
  {
    id: "people-influence",
    driverId: "people",
    name: "Influence",
    definition: "Makes ideas clear, adapts communication to the audience, and creates understanding that helps people act, decide, or align.",
    coreQuestion: "Can this person communicate clearly, adapt to the audience, and positively influence",
    levels: [
      {
        level: 1,
        label: "Unclear",
        humanDescriptor: "Struggles to express ideas effectively; communication lacks clarity, structure, or relevance, making it difficult for others to understand or engage.",
        aiDescriptor: "• Struggles to communicate ideas clearly\n• Provides incomplete, confusing, or poorly structured explanations\n• Fails to adjust communication when misunderstanding occurs\n• Creates uncertainty or ambiguity for others",
      },
      {
        level: 2,
        label: "Emerging",
        humanDescriptor: "Expresses thoughts and ideas but communication is often unstructured, incomplete, or difficult for others to follow consistently.",
        aiDescriptor: "• Expresses thoughts or opinions but lacks clear structure\n• Communicates inconsistently across situations\n• Provides partial explanations that require clarification\n• Relies heavily on others to interpret or organize messages",
      },
      {
        level: 3,
        label: "Expressive",
        humanDescriptor: "Communicates clearly and understandably; conveys ideas in a logical and effective manner that enables understanding and productive discussion.",
        aiDescriptor: "• Communicates ideas clearly and logically\n• Explains concepts in ways others can understand\n• Structures messages effectively\n• Facilitates productive discussion or understanding",
      },
      {
        level: 4,
        label: "Adaptive",
        humanDescriptor: "Adapts messages to different audiences and situations; considers perspective, context, and communication style to improve understanding and engagement.",
        aiDescriptor: "• Adapts communication to different audiences or situations\n• Considers the perspective or needs of others when communicating\n• Adjusts communication style to improve understanding\n• Addresses questions, concerns, or misunderstandings effectively",
      },
      {
        level: 5,
        label: "Influential",
        humanDescriptor: "Creates understanding that shapes actions, decisions, or outcomes; builds alignment and inspires commitment through clear, purposeful communication.",
        aiDescriptor: "• Creates shared understanding\n• Builds alignment through purposeful communication\n• Inspires commitment or engagement that influences actions or decisions\n• Communicates in ways that positively shape outcomes",
      },
    ],
  },
  {
    id: "people-collaboration",
    driverId: "people",
    name: "Collaboration & Inclusion",
    definition: "Works with others in a way that builds trust, invites diverse perspectives, creates shared ownership, and strengthens collective outcomes.",
    coreQuestion: "Can this person work effectively with people toward shared outcomes?",
    levels: [
      {
        level: 1,
        label: "Isolated",
        humanDescriptor: "Works largely independently and demonstrates limited awareness of the value others bring; may overlook opportunities to collaborate or incorporate different perspectives.",
        aiDescriptor: "• Works primarily in isolation\n• Demonstrates limited collaboration or shared ownership\n• Overlooks contributions or perspectives from others\n• Focuses mainly on individual objectives",
      },
      {
        level: 2,
        label: "Participative",
        humanDescriptor: "Contributes to group efforts when required and works reasonably well with others, but collaboration tends to be transactional and limited to immediate responsibilities.",
        aiDescriptor: "• Participates in team activities when required\n• Contributes to group efforts appropriately\n• Collaborates within defined responsibilities\n• Demonstrates limited proactive engagement with others",
      },
      {
        level: 3,
        label: "Collaborative",
        humanDescriptor: "Actively works with others, shares ownership, and contributes constructively toward common goals; values teamwork and supports collective success.",
        aiDescriptor: "• Shares ownership of goals or outcomes\n• Supports teammates and contributes constructively\n• Collaborates effectively to achieve common objectives\n• Values teamwork and collective success",
      },
      {
        level: 4,
        label: "Inclusive",
        humanDescriptor: "Actively seeks diverse perspectives, creates an environment where others feel heard and valued, and leverages different viewpoints to improve decisions and outcomes.",
        aiDescriptor: "• Actively seeks diverse perspectives\n• Ensures others feel heard and included\n• Incorporates different viewpoints into decisions or solutions\n• Leverages diversity to improve outcomes",
      },
      {
        level: 5,
        label: "Unifying",
        humanDescriptor: "Builds trust and shared ownership across diverse individuals or groups, resolves differences constructively, and strengthens collective outcomes by bringing people together around common goals.",
        aiDescriptor: "• Builds trust and shared ownership across individuals or groups\n• Resolves differences or tensions constructively\n• Brings people together around common goals\n• Strengthens collective outcomes through collaboration",
      },
    ],
  },
  {
    id: "people-capability",
    driverId: "people",
    name: "Grows Capability",
    definition: "Seeks feedback, learns from experience, applies new knowledge, improves over time, and helps others grow through shared learning.",
    coreQuestion: "Can this person continuously get better and help others grow where appropriate?",
    levels: [
      {
        level: 1,
        label: "Static",
        humanDescriptor: "Shows limited interest in feedback or learning and tends to rely on familiar approaches without reflecting on opportunities for improvement.",
        aiDescriptor: "• Relies heavily on familiar approaches\n• Demonstrates limited reflection or self-improvement\n• Resists or ignores feedback\n• Repeats mistakes without learning from them",
      },
      {
        level: 2,
        label: "Receptive",
        humanDescriptor: "Accepts feedback and learning opportunities when provided but applies them inconsistently and depends largely on external guidance for development.",
        aiDescriptor: "• Accepts feedback when provided\n• Participates in learning opportunities when encouraged\n• Demonstrates inconsistent application of learning\n• Relies primarily on external guidance for development",
      },
      {
        level: 3,
        label: "Developing",
        humanDescriptor: "Actively seeks opportunities to learn and improve, applies lessons from experience, and demonstrates visible growth over time.",
        aiDescriptor: "• Actively seeks feedback or learning opportunities\n• Applies lessons from experience\n• Demonstrates improvement over time\n• Learns new skills or approaches when needed",
      },
      {
        level: 4,
        label: "Intentional",
        humanDescriptor: "Pursues development deliberately, uses feedback systematically, and continuously refines approaches to improve capability and performance.",
        aiDescriptor: "• Pursues development deliberately\n• Uses feedback systematically to improve performance\n• Reflects on successes and failures to refine approaches\n• Continuously upgrades capability through intentional learning",
      },
      {
        level: 5,
        label: "Growth Catalyst",
        humanDescriptor: "Accelerates learning beyond personal development by sharing knowledge, helping others improve, and creating an environment that encourages growth and continuous learning.",
        aiDescriptor: "• Shares knowledge or lessons learned with others\n• Helps others improve or develop\n• Creates opportunities for collective learning\n• Promotes a culture of growth and continuous improvement",
      },
    ],
  },
  {
    id: "mastery-functional",
    driverId: "mastery",
    name: "Functional Knowledge",
    definition: "Understands the concepts, tools, methods, and standards that matter in the target role, and explains why they matter in real work.",
    coreQuestion: "Can this person understand the technical craft required for the target role?",
    levels: [
      {
        level: 1,
        label: "Inaccurate",
        humanDescriptor: "Misunderstands, misuses, or inaccurately explains the technical concept, tool, method, or domain requirement.",
        aiDescriptor: "• Defines the concept, tool, or method incorrectly, or confuses it with another concept\n• Misses the core purpose or primary use of the concept in the target role\n• Uses relevant terminology in a way that shows misunderstanding\n• Gives an explanation that would likely lead to incorrect or ineffective use in practice",
      },
      {
        level: 2,
        label: "Basic",
        humanDescriptor: "Recognizes the concept, tool, or method but explains it in a basic, generic, incomplete, or shallow way. Has awareness of the topic but lacks enough clarity, completeness, role relevance, or practical understanding to demonstrate job-ready knowledge.",
        aiDescriptor: "• Provides a simple definition without explaining practical role use\n• Identifies only basic features, functions, or steps\n• Gives generic examples that are weakly connected to the target role\n• Omits important parts of when, why, or how the concept is used",
      },
      {
        level: 3,
        label: "Sound",
        humanDescriptor: "Explains the concept, tool, method, or domain requirement correctly and clearly in a way that is relevant to the target role. Demonstrates enough technical understanding to operate effectively in familiar role situations.",
        aiDescriptor: "• Explains the concept accurately using role-relevant language\n• Identifies the main uses, components, inputs, outputs, or steps involved\n• Connects the concept to target role tasks, tools, or deliverables\n• Gives a practical example showing how the concept supports familiar role situations",
      },
      {
        level: 4,
        label: "Advanced",
        humanDescriptor: "Explains the concept in context, including when and why it is used, relevant constraints, practical considerations, limitations, and trade-offs. Shows strong professional judgement and goes beyond a correct definition by connecting the concept to real role situations.",
        aiDescriptor: "• Explains when and why the concept should be used in different role situations\n• Identifies constraints, limitations, prerequisites, or risks that affect use\n• Explains trade-offs linked to using the concept, method, or tool\n• Connects the concept to role-specific decisions, quality standards, or outcomes",
      },
      {
        level: 5,
        label: "Mastery",
        humanDescriptor: "Explains the concept as part of a broader role system. Handles complexity, ambiguity, dependencies, edge cases, and optimization. Shows how the concept connects to performance, quality, decision-making, or broader business outcomes.",
        aiDescriptor: "• Connects the concept to the broader workflow, operating model, or role system\n• Explains dependencies between the concept and related tools, processes, data, or stakeholders\n• Addresses edge cases, exceptions, or ambiguous conditions that affect use\n• Explains how better use of the concept can improve performance, quality, efficiency, or outcomes",
      },
    ],
  },
  {
    id: "mastery-execution",
    driverId: "mastery",
    name: "Execution",
    definition: "Turns role knowledge into practical, well-structured work by choosing appropriate methods, using tools effectively, and producing sound outcomes.",
    coreQuestion: "Can this person use the technical knowledge required for the role in practical work",
    levels: [
      {
        level: 1,
        label: "Inaccurate",
        humanDescriptor: "Applies the wrong method, misunderstands the practical requirement, gives an unstructured or technically weak response, or proposes actions that would likely produce poor-quality work. Shows limited ability to use role-specific knowledge in practice.",
        aiDescriptor: "• Misunderstands the scenario requirement or expected deliverable\n• Selects a method, tool, or process that does not fit the situation\n• Omits critical steps needed for the work to be viable\n• Proposes actions that conflict with basic role standards or expected quality",
      },
      {
        level: 2,
        label: "Basic",
        humanDescriptor: "Identifies some relevant actions but the approach remains generic, incomplete, weakly sequenced, or insufficiently connected to the scenario. Shows partial practical awareness but does not yet demonstrate job-ready technical application.",
        aiDescriptor: "• Lists basic actions without clear sequence or decision logic\n• Applies a generic approach that is not tailored to the scenario details\n• Names relevant tools or methods without explaining how they would be used\n• Leaves key outputs, quality checks, or success criteria undefined",
      },
      {
        level: 3,
        label: "Sound",
        humanDescriptor: "Provides a clear, technically correct, and role-relevant approach to the scenario. Demonstrates logical steps, appropriate methods, and enough practical understanding to handle familiar role situations effectively.",
        aiDescriptor: "• Sequences role-relevant steps from problem understanding to delivery\n• Uses appropriate tools, methods, or processes and explains how they apply\n• Defines the expected output, deliverable, or success measure\n• Includes basic checks to ensure the work is accurate, complete, or usable",
      },
      {
        level: 4,
        label: "Advanced",
        humanDescriptor: "Adapts the approach to the specific situation, recognizes constraints, manages trade-offs, considers risks, and demonstrates practical professional judgement. Can apply technical knowledge beyond a standard playbook.",
        aiDescriptor: "• Adapts the approach to specific constraints such as time, budget, data, customer, market, or stakeholder needs\n• Explains trade-offs behind technical choices\n• Identifies material risks or dependencies and how they would be managed\n• Adjusts the approach based on scenario context or changing conditions",
      },
      {
        level: 5,
        label: "Mastery",
        humanDescriptor: "Handles complexity, ambiguity, dependencies, edge cases, and optimization within the scenario.",
        aiDescriptor: "• Integrates multiple technical considerations into a coherent end-to-end solution\n• Handles ambiguity or edge cases by stating assumptions, decision points, or contingencies\n• Connects technical choices to broader role outcomes, quality, performance, or sustainability\n• Optimizes the approach using feedback, data, or early performance signals",
      },
    ],
  },
  {
    id: "mastery-innovation",
    driverId: "mastery",
    name: "Innovation",
    definition: "Makes technical work better by identifying improvement opportunities, testing better approaches, learning from results, and improving quality, efficiency, or impact.",
    coreQuestion: "Can this person improve the technical craft, process, output, or outcome required for the",
    levels: [
      {
        level: 1,
        label: "Inaccurate",
        humanDescriptor: "Misunderstands the improvement problem, proposes irrelevant or technically weak changes, or suggests actions that are unlikely to improve the outcome. Shows limited ability to identify or improve technical work.",
        aiDescriptor: "• Misidentifies the improvement problem or root issue\n• Proposes changes unrelated to the technical issue or desired outcome\n• Relies on unsupported opinions without evidence or diagnosis\n• Ignores basic feasibility, quality, or risk implications",
      },
      {
        level: 2,
        label: "Basic",
        humanDescriptor: "Suggests simple or obvious improvements but does not clearly diagnose the issue, explain why the improvement would work, or define how success would be assessed. Shows basic improvement awareness but remains generic or underdeveloped.",
        aiDescriptor: "• Suggests obvious or generic improvements without diagnosing cause\n• Focuses on activity changes without linking them to the outcome\n• Uses limited evidence or metrics to justify the improvement\n• Does not explain how the improvement would be tested or assessed",
      },
      {
        level: 3,
        label: "Sound",
        humanDescriptor: "Identifies a relevant improvement area, proposes practical technical changes, and explains how improvement would be measured. The answer demonstrates enough improvement thinking to enhance familiar role tasks, outputs, or processes.",
        aiDescriptor: "• Identifies a relevant improvement area linked to the role outcome\n• Proposes practical technical changes aligned to the problem\n• Defines how success or improvement would be measured\n• Uses available feedback, data, or observed results to refine the approach",
      },
      {
        level: 4,
        label: "Advanced",
        humanDescriptor: "Diagnoses likely causes, prioritizes improvement actions, considers constraints and trade-offs, tests changes systematically, and refines the approach based on results. The answer shows advanced technical judgement in improving work beyond obvious fixes.",
        aiDescriptor: "• Diagnoses likely causes before selecting improvement actions\n• Prioritizes improvements based on impact, effort, constraints, or risk\n• Tests changes systematically and iterates based on results\n• Explains trade-offs, side effects, or implementation risks",
      },
      {
        level: 5,
        label: "Mastery",
        humanDescriptor: "Treats improvement as part of a broader technical system. Handles complexity, dependencies, edge cases, downstream impact, and sustainable optimization. It demonstrates mastery-level judgement in improving quality, efficiency, performance, or impact over time.",
        aiDescriptor: "• Connects improvement to the broader system, dependencies, or long-term performance\n• Designs an ongoing improvement loop rather than a one-off fix\n• Anticipates downstream impacts across users, processes, quality, or business outcomes\n• Optimizes for sustainable quality, efficiency, or impact under changing conditions",
      },
    ],
  },
];
